{% set version = "7.0.0" %}
{% set sha256 = "63e454202f72796044e99846881c33767c47fa050735dc1f927657b9cd2b7fcd" %}

package:
  name: ipywidgets
  version: {{ version }}

source:
  fn: ipywidgets-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipywidgets/ipywidgets-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python -m pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - ipython >=4.0.0
    - ipykernel >=4.5.1
    - traitlets >=4.3.1,<5.0.0
    - widgetsnbextension >=2.0.0,<3.0.0
    - nbformat >=4.2.0

test:
  imports:
    - ipywidgets

about:
  home: https://github.com/ipython/ipywidgets
  license: BSD 3-clause
  license_file: COPYING.md
  summary: Jupyter Interactive Widgets

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - jasongrout
    - maartenbreddels
